
--USERNAME:MANAGER   PASSWORD:Admin123456789
CREATE USER MANAGER IDENTIFIED BY Admin123456789;
GRANT CREATE SESSION TO MANAGER;
GRANT SELECT ON PAYMENT TO MANAGER;
GRANT SELECT ON DISHRECIPE TO MANAGER;
GRANT SELECT ON DINEINORDER TO MANAGER;
GRANT SELECT ON DELIVERYORDER TO MANAGER;
GRANT SELECT ON CUSTOMER TO MANAGER;
GRANT SELECT ON EMPLOYEE TO MANAGER;
GRANT INSERT ON EMPLOYEE TO MANAGER;
GRANT UPDATE ON EMPLOYEE TO MANAGER;
GRANT SELECT ON INVENTORY TO MANAGER;
GRANT INSERT ON INVENTORY TO MANAGER;
GRANT UPDATE ON INVENTORY TO MANAGER;
GRANT SELECT ON MENU TO MANAGER;
GRANT INSERT ON MENU TO MANAGER;
GRANT UPDATE ON MENU TO MANAGER;
GRANT SELECT ON DININGTABLE TO MANAGER;
GRANT INSERT ON DININGTABLE TO MANAGER;
GRANT UPDATE ON DININGTABLE TO MANAGER;
GRANT SELECT ON RESERVATION TO MANAGER;
GRANT INSERT ON RESERVATION TO MANAGER;
GRANT UPDATE ON RESERVATION TO MANAGER;

--USERNAME:ATTENDANT   PASSWORD:Admin123456789
CREATE USER ATTENDANT IDENTIFIED BY Admin123456789;
GRANT CREATE SESSION TO ATTENDANT;
GRANT SELECT ON RESERVATION TO ATTENDANT;
GRANT SELECT ON ATTENDANT TO ATTENDANT;
GRANT SELECT ON DINEINORDER TO ATTENDANT;
GRANT SELECT ON DELIVERYORDER TO ATTENDANT;
GRANT SELECT ON MENU TO ATTENDANT;
GRANT SELECT ON EMPLOYEE TO ATTENDANT;
GRANT INSERT ON EMPLOYEE TO ATTENDANT;
GRANT UPDATE ON EMPLOYEE TO ATTENDANT;

--USERNAME:DELIVERYAGENT   PASSWORD:Admin123456789
CREATE USER DELIVERYAGENT IDENTIFIED BY Admin123456789;
GRANT CREATE SESSION TO DELIVERYAGENT;
GRANT SELECT ON DELIVERYORDER TO DELIVERYAGENT;
GRANT SELECT ON DELIVERYAREA TO DELIVERYAGENT;
GRANT SELECT ON EMPLOYEE TO DELIVERYAGENT;
GRANT INSERT ON EMPLOYEE TO DELIVERYAGENT;
GRANT UPDATE ON EMPLOYEE TO DELIVERYAGENT;

--USERNAME:CUSTOMER   PASSWORD:Admin123456789
CREATE USER CUSTOMER IDENTIFIED BY Admin123456789;
GRANT CREATE SESSION TO CUSTOMER;
GRANT SELECT ON MENU TO CUSTOMER;
GRANT SELECT ON PAYMENT TO CUSTOMER;
GRANT SELECT ON CUSTOMER TO CUSTOMER;
GRANT INSERT ON CUSTOMER TO CUSTOMER;
GRANT UPDATE ON CUSTOMER TO CUSTOMER;